apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
  containers:
  - name: mysql
    image: mysql/mysql-server
    envFrom:
    - secretRef:
        name: istory-db-secret
    - configMapRef:
        name: istory-db-config
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    volumeMounts:
      - name: mysql-persistent-storage
        mountPath:  /var/lib/mysql
    ports:
      - containerPort: 3306
