version: '3.6'
name: mysql

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.0
    ports:
    - 3306:3306
    networks:
      - kind_network
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: istory
      MYSQL_ROOT_PASSWORD: admin123

networks:
  kind_network:
    name: kind
    external: true