name: first-workflow
on: [push] # push event 발생 시

job: 
  shell-cmd-job:
    runs-on: ubuntu-latest # 해당 job을 ubuntu latest 버전에서 돌려라
    steps: 
      - name: echo Hello
        run: echo "Hello World"
      - name: multiple line command 
        run: | 
          node -v 
          npm -v
